### ISSUE TITLE
Layout - Grid Path: size not draggable

### ISSUE THREAD

**Issue by qlcplusme** [norbertrostaing/BlinderKitten#10]
Not a big issue,
on a Gnome desktop, the xParam and yParam of the Grid Path cannot be dragged with the mouse, the value gets too big, the other parameters do work normally.
If I drag them ultra gently, or with Alt pressed, the parameter jumps from 0 to the original value, then directly to a huge number.
![Screenshot from 2024-08-08 23-05-58](https://github.com/user-attachments/assets/d75e08ed-9c82-40d4-ac46-90ddf25b8a06)
![Screenshot from 2024-08-08 23-06-56](https://github.com/user-attachments/assets/dd59eb2f-1252-4ebc-83e0-ff686d811c1e)

**Comment by norbertrostaing** [comment]
Thanks for the feedback, It will be fixed in the next beta :)

**Comment by norbertrostaing** [comment]
fixed in the next version
