### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by vanous** [norbertrostaing/BlinderKitten#3]
Hi @norbertrostaing ,

how can i help to improve the documentation? Here is a small section i had written for the [My first hand made fixture](https://norbertrostaing.gitbook.io/blinderkitten/first-steps/my-first-hand-made-fixture) page:

---
## Importing fixture types from GDTF

Fixture types can either be [created manually](#fixture-type) or can be
imported from GDTF files. The General Device Type Format (GDTF) is an open
standard for describing devices of the entertainment industry.

To search for and download GDTF files, head to [GDTF
Share](https://gdtf-share.com/index.php), create a free account, then sign in.
Search for and download the GDTF file for the fixture you need. Note: a single
GDTF file contains all DMX Modes for the device. 

In BlinderKitten, go to menu: `File` → `Import…` and select the previously
downloaded GDTF file. After (successful) import, you can see the newly imported
fixture types in the `Fixture Types` list.

---

What do you think?
Thank you

**Comment by norbertrostaing** [comment]
Thanks a lot for your contribution, I've created a page GDTF import in the documentation.

**Comment by hyperglue** [comment]
Hey, 

would it be possible to create a GitHub repository for documentation too? That way it'd be easier contribute for anyone as any changes could be accepted as pull requests.
